logging:
  level:
    dev.ell.mrgreen: DEBUG

management:
  otlp:
    metrics:
      export:
        enabled: false
  tracing:
    sampling:
      probability: 0
    export:
      otlp:
        enabled: false
