spring:
  main:
    web-application-type: none
  application:
    name: "mrgreen"

discord:
  token: ${DISCORD_TOKEN}
  client-id: ${DISCORD_CLIENT_ID}
  prefix: "%"
  bridge-bot-ids: ${DISCORD_BRIDGE_BOT_IDS:}

google:
  api-key: ${GOOGLE_API_KEY}

management:
  otlp:
    metrics:
      export:
        url: ${GRAFANA_OTLP_ENDPOINT:}
        headers:
          Authorization: ${GRAFANA_OTLP_AUTH_HEADER:}
        step: 60s
  tracing:
    sampling:
      probability: 1.0
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: ${GRAFANA_OTLP_TRACE_ENDPOINT:}
          headers:
            Authorization: ${GRAFANA_OTLP_AUTH_HEADER:}
