spring:
  main:
    web-application-type: none
  application:
    name: "mrgreen"
  datasource:
    url: jdbc:sqlite:${DB_PATH:mrgreen.db}
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

discord:
  token: ${DISCORD_TOKEN}
  client-id: ${DISCORD_CLIENT_ID}
  prefix: "%"
  bridge-bot-ids: ${DISCORD_BRIDGE_BOT_IDS:}

google:
  api-key: ${GOOGLE_API_KEY}

twitch:
  client-id: ${TWITCH_CLIENT_ID}
  client-secret: ${TWITCH_CLIENT_SECRET}

management:
  otlp:
    metrics:
      export:
        url: ${GRAFANA_OTLP_ENDPOINT:}
        headers:
          Authorization: ${GRAFANA_OTLP_AUTH_HEADER:}
        step: 60s
  tracing:
    sampling:
      probability: 1.0
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: ${GRAFANA_OTLP_TRACE_ENDPOINT:}
          headers:
            Authorization: ${GRAFANA_OTLP_AUTH_HEADER:}
